#!/usr/bin/env bash
# Installing nginx on our webserver
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
service nginx start
