#!/usr/bin/env bash
# Installing nginx on our webserver
sudo apt-get -y update
sudo apt-get -y install nginx

#sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx start
