#!/usr/bin/env bash
# redirect nginx server to another page
# with /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/JohnNyokabi permanent;/' /etc/ngnx/sites-available/default
service nginx start
