#!/usr/bin/env bash
# redirect nginx server to another page
# with /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo sed -i '/^# Default server configuration/a\\
	location /redirect_me {\n
		return 301 http://www/github.com/JohnNyokabi;\n
	}\n' /etc/nginx/sites-available/default
sudo service nginx restart
