#!/usr/bin/env bash
# Install the load balanecer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend front
        bind *:80
	mode http
	default_backend back
backend back
	mode http
        balance roundrobin
        server 122619-web-01 34.203.29.182
        server 122619-web-02 54.236.24.31" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
