#!/usr/bin/env bash
# Install the load balanecer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend front
        bind *:80
	default_backend back
backend back
        balance roundrobin
        server 122619-web-01 100.27.14.80:80 check
        server 122619-web-02 54.236.24.31:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
