#!/usr/bin/env bash
# clock that displays 12 hours and 59 minutes

hour=-1

while [ $((++hour)) -le 12 ]; do
	echo Hour: $hour
	minute=0
	while [ $((++minute)) -le 59 ]; do
		echo $minute
	done
done

