#!/usr/bin/env bash
# Configure nginx to run as user nginx on port 8080
chmod 777 /etc/nginx/nginx.conf
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start