#!/usr/bin/env bash
# Script for stopping Gunicorn gracefully

worker_pids=$(pgrep gunicorn)
for pid in $worker_pids; do
    kill -s HUP $pid
done

# Verify if the reload was successful
new_worker_pids=$(pgrep gunicorn)

if [[ "$worker_pids" == "$new_worker_pids" ]]; then
    echo "NOk"
else
    echo "OK"
fi
